apiVersion: v1
kind: Service
metadata:
  name: python-microservice-lb
  namespace: microservice
  labels:
    app: python-microservice
spec:
  type: LoadBalancer
  selector:
    app: python-microservice
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
